name: Node CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: NPM Install
      run: npm ci
    - name: NPM Lint
      run: npm run lint
    - name: Format Check
      run: npm run format-check
    - name: NPM Build
      run: npm run build --if-present
      env:
        CI: true
